version: '3'

services:
  itcrm:
    container_name: itcrm
    image: itcrm:test
    build: 
      context: .
      dockerfile: .docker/Dockerfile
    configs:
      - source: itcrm_php_conf
        target: /usr/local/etc/php/conf.d/php.ini
    networks:
      - itcrm

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - '33000:80'
    configs:
      - source: itcrm_nginx_conf
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - /Users/alexremn/Documents/work/git/brainq/ishosting/ish-admin-markup:/var/www/html
    depends_on:
      - itcrm
    networks:
      - itcrm

configs:
  itcrm_nginx_conf:
    file: .docker/configs/default.conf
  itcrm_php_conf:
    file: .docker/configs/php.ini

networks:
  itcrm:
    driver: bridge
