app_index:
  path: /
  controller: App\Controller\IndexController::index


app_ololo:
  path: /ololo
  controller: App\Controller\IndexController::ololo

app_home:
  path: /home
  controller: App\Controller\IndexController::home